adding some more mathematical shapes
openMetadataInitiative/openMINDS_SANDS pull request #187
Opened 2022-08-09 08:36 UTC by lzehl

related to #186

2022-08-09 09:33 UTC, lzehl commented
@xgui3783 and @apdavison before I continue here I would need your feedback.
Goal of these schemas are to define mathematical shapes without defining an actual coordinate space.

Which one do we most likely need ? How do we define them best / consistently ?

2022-08-09 10:32 UTC, xgui3783 commented
My immediate focus is that (IMO) all are 2D shapes, except sphere, which IMO is a 3D concept. Its 2D concept would be a circle. 

I can Imagine circle used. 

Would line segment also be included (or is it already included in a previous commit?)

Seems strange to not have rectangle, though one would argue that a rectangle is a special parallelogram. But the same can be said for square.

2022-08-09 11:05 UTC, lzehl commented
@xgui3783 #186 has various 3D shapes besides sphere. But before I implement them I wanted to have feedback.

I would define a line as a coordinate point only within a given space. Therefore it is excluded here from mathematical shapes that are defined without a space. There will be another PR in connection with the annotation revision with a Contour schema (which can be a line).

Note that circle, rectangle and ellipse were already added to mathematical shapes in a previous PR.

2026-02-24 14:22 UTC, lzehl commented
There can be more added but I would like to clarify first if we want all of them for convenience or if we want to kick out all the ones that are theoretically covered by general classes.

**Note:** mathematical shapes should be space independent represented (since they are later to be placed an a coordinate framework). For this reason I avoided terms such as height, depth, etc

2026-02-24 14:41 UTC, Raphael-Gazzotti commented on schemas/mathematicalShape/cube.schema.tpl.json
> +    "mathematical2DShape"
```suggestion
    "mathematical3DShape"
```

A cube is a 3D shape.

2026-02-24 14:45 UTC, lzehl commented on schemas/mathematicalShape/cube.schema.tpl.json
> +    "mathematical2DShape"
damn overlooked that one

2026-02-24 14:46 UTC, lzehl commented on schemas/mathematicalShape/cube.schema.tpl.json
> +    "mathematical2DShape"
hope there are not more... but I worked late yesterday and today did several things in parallel :see_no_evil:

2026-02-24 14:47 UTC, lzehl commented on schemas/mathematicalShape/cube.schema.tpl.json
> +    "mathematical2DShape"
fixed

2026-02-24 15:04 UTC, Raphael-Gazzotti commented on schemas/mathematicalShape/ellipsoid.schema.tpl.json
Not certain about this, if we want to align with Ellipse, it should be a diameters array containing three values.

2026-02-25 07:18 UTC, Raphael-Gazzotti commented on schemas/mathematicalShape/ellipsoid.schema.tpl.json
One suggestion would be to embed Ellipse (instead of majorDiameter/minorDiameter) and keep intermediateDiameter. But it is probably not valid since an Ellipsoid is not a kind of Ellipse.

2026-02-25 12:52 UTC, Raphael-Gazzotti commented on schemas/mathematicalShape/kite.schema.tpl.json
> +    },
Based on the instruction, I would expect this property to be defined as an array.

2026-02-27 09:45 UTC, Raphael-Gazzotti commented on schemas/mathematicalShape/regularPolygon.schema.tpl.json
I see why EquilateralTriangle was introduced (to support equilateralTriangularPyramid.schema.tpl.json and equilateralTriangularPrism.schema.tpl.json). However, an equilateral triangle could be defined as a specific case of RegularPolygon. I am unsure whether this duplication across shapes is intentional.

2026-02-27 10:07 UTC, Raphael-Gazzotti reviewed
General comment:
I am not sure all the specialized prism, pyramid, frustum shapes are necessary. We could define a general Prism/Pyramid/Frustum with a baseShape property using _embeddedTypes (e.g., Rectangle, Triangle, etc.). This would provide the same flexibility while avoiding multiple specialized prism/pyramid/frustum schemas. That said, specialized variants may still be justified if certain techniques or devices depend on explicitly defined shapes.

For the arrays of QuantitativeValue, it’s unclear whether the values are expected to follow a specific order (e.g., major and minor diameters for an ellipse). if ordering matters, this should be clearly specified in the instructions.

2026-02-27 10:58 UTC, lzehl commented on schemas/mathematicalShape/kite.schema.tpl.json
> +    },
Indeed. I forgot to update this

2026-02-27 11:02 UTC, lzehl commented on schemas/mathematicalShape/ellipsoid.schema.tpl.json
An ellipsoid which can be represented as ellipse + intermediateDiameter is only a special case of an ellipsoid called spheroid.

2026-02-27 11:07 UTC, lzehl commented on schemas/mathematicalShape/regularPolygon.schema.tpl.json
it is since the current approach would create parent shapes and their important child shapes.

e.g. 
- rhombus is a special case of kite
- square is a special case of rectangle
- square and equilateral triangle are both special cases of regular polygon
etc.

2026-02-27 11:26 UTC, Raphael-Gazzotti approved these changes

2026-03-03 11:52 UTC, Raphael-Gazzotti commented on schemas/mathematicalShape/centroidalPyramid.schema.tpl.json
> +      ]
```suggestion
      "_embeddedCategories": [
        "simplePolygon"
      ]
```

2026-03-03 12:03 UTC, Raphael-Gazzotti requested changes

2026-03-03 16:57 UTC, Raphael-Gazzotti approved these changes

2026-03-03 16:57 UTC, merged