Clean up: brain atlas version
openMetadataInitiative/openMINDS_SANDS pull request #219
Opened 2023-02-16 13:02 UTC by UlrikeS91

MINOR changes:
- improved instructions 
- renamed `atlasType` to `type` to reduce list of properties & because of new convention to use type when the additional information is not adding any other meaning than imposed by schema already 
- renamed `hasTerminologyVersion` to `hasTerminology` to reduce list of property names and follow new convention to not add "version" to an existing property name (no need to differentiate since the expected values are limited to versions)

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-21 15:21 UTC, lzehl requested changes

2023-02-21 15:21 UTC, lzehl commented on schemas/atlas/brainAtlasVersion.schema.tpl.json
> +      "_instruction": "Add brain atlas version preceding this brain atlas version.",
"Add the ..." ?

2023-03-09 11:10 UTC, lzehl approved these changes

2023-03-09 11:10 UTC, lzehl commented
@aeidi89 please have a second look and merge if you also approve

2023-03-10 09:35 UTC, aeidi89 commented on schemas/atlas/brainAtlasVersion.schema.tpl.json
> +      "_instruction": "Enter the parcellation terminology version of this brain atlas version.",
Should this still have 'version' in or not?

@lzehl

2023-03-10 09:36 UTC, aeidi89 requested changes
Looks good, with the minor exception of one word in one of the instructions (see comment)

2023-03-10 10:11 UTC, merged