Clean up: common coordinate space version
openMetadataInitiative/openMINDS_SANDS pull request #223
Opened 2023-02-16 13:25 UTC by UlrikeS91

MINOR changes:
- improved instructions 
- establish alphabetical order
- establish correct order within a property

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-21 15:29 UTC, lzehl requested changes

2023-02-21 15:29 UTC, lzehl commented on schemas/atlas/commonCoordinateSpaceVersion.schema.tpl.json
> +      "_instruction": "Enter the origin (= the central point where all axes intersect) of this common coordinate space version for two-dimensonal spaces as [x, y] or for three-dimensional space as [x
"Enter the origin (central point where all axes intersect) of this common coordinate space version for two-dimensional spaces as [x, y] or for three-dimensional space as [x, y, z]."

2023-03-09 11:17 UTC, lzehl approved these changes
@aeidi89 I've updated the file in accordance with my issue. Please double check and merge if you also approve now.

2023-03-10 09:32 UTC, aeidi89 approved these changes
Looks good

2023-03-10 09:32 UTC, merged