Clean up: custom coordinate space
openMetadataInitiative/openMINDS_SANDS pull request #227
Opened 2023-02-16 13:37 UTC by UlrikeS91

MINOR changes:
- improved instructions 
- establish correct order within a property

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-21 15:35 UTC, lzehl requested changes

2023-02-21 15:35 UTC, lzehl commented on schemas/non-atlas/customCoordinateSpace.schema.tpl.json
> +      "_instruction": "Enter the origin (= the central point where all axes intersect) of this common coordinate space for two-dimensonal spaces as [x, y] or for three-dimensional space as [x, y, z].
"Enter the origin (central point where all axes intersect) of this common coordinate space for two-dimensional spaces as [x, y] or for three-dimensional space as [x, y, z]."

2023-03-09 11:19 UTC, lzehl approved these changes
@aeidi89 I've updated the file in regard to my issue. Please double check and merge if you also approve now.

2023-03-10 09:30 UTC, aeidi89 commented on schemas/non-atlas/customCoordinateSpace.schema.tpl.json
> +      "_instruction": "Enter the origin (central point where all axes intersect) of this common coordinate space for two-dimensional spaces as [x, y] or for three-dimensional space as [x, y, z].",
As this is the custom coordinate space schema, shouldn't the instructions point to custom and not common coordinate space?

2023-03-10 09:33 UTC, aeidi89 approved these changes
I fixed a minor typo, changing 'common' to 'custom' in the instruction

2023-03-10 09:33 UTC, merged