Update README.md
openMetadataInitiative/openMINDS_SANDS pull request #275
Opened 2023-10-26 10:28 UTC by lzehl

modified similar to the one from core

2024-05-30 07:45 UTC, UlrikeS91 requested changes
One small typo. Otherwise fine to merge.

2024-05-30 07:45 UTC, UlrikeS91 commented on README.md
> +The openMINDS_SANDS repository repository hosts one of the metadata models of the **openMINDS metadata framework**. It defines modular metadata schemas for **s**patial **a**nchoring of **n**euroscien
"The openMINDS_SANDS repository repository [...]" remove one "repository"

2024-06-04 07:02 UTC, lzehl commented
@UlrikeS91 this PR was outdated in any case. I've made now the updates.

2024-06-04 11:24 UTC, UlrikeS91 requested changes
The svgs don't seem to match the pngs, could you check if you uploaded the correct svgs or pngs depending on which one is the one you want to keep?

2024-06-04 12:53 UTC, UlrikeS91 approved these changes

2024-06-04 12:53 UTC, merged